import '../models/place.dart';
import '../models/review.dart';
import '../models/user_profile.dart';

class MockData {
  static const UserProfile currentUser = UserProfile(
    uid: 'user-me',
    displayName: 'Pedro Otávio',
    handle: '@pedrootavio',
    photoUrl: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=200&q=80',
    bio: 'Explorador da gastronomia paulistana e caçador dos melhores cafés e pães artesanais.',
    homeCityName: 'São Paulo - SP',
    followersCount: 54,
    followingCount: 42,
  );

  static final List<Place> places = [
    const Place(
      id: 'p1',
      name: 'Mani',
      category: 'Restaurante Contemporâneo',
      address: 'Rua Joaquim Antunes, 210 - Pinheiros',
      neighborhood: 'Pinheiros',
      city: 'São Paulo',
      rating: 4.9,
      reviewsCount: 142,
      priceLevel: '\$\$\$\$',
      photoUrl: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=600&q=80',
      lat: -23.561684,
      lng: -46.682371,
      tags: ['Alta Gastronomia', 'Estrela Michelin', 'Romântico'],
      openingHours: '19:30 - 23:30',
    ),
    const Place(
      id: 'p2',
      name: 'Coffee Lab',
      category: 'Cafeteria Especial',
      address: 'Rua Fradique Coutinho, 1340 - Vila Madalena',
      neighborhood: 'Vila Madalena',
      city: 'São Paulo',
      rating: 4.8,
      reviewsCount: 230,
      priceLevel: '\$\$',
      photoUrl: 'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?auto=format&fit=crop&w=600&q=80',
      lat: -23.557431,
      lng: -46.691892,
      tags: ['Cafés Especiais', 'Trabalho/Estudo', 'Artesanal'],
      openingHours: '09:00 - 18:00',
    ),
    const Place(
      id: 'p3',
      name: 'Fabrique Pão e Café',
      category: 'Padaria Artesanal',
      address: 'Rua Itacolomi, 612 - Higienópolis',
      neighborhood: 'Higienópolis',
      city: 'São Paulo',
      rating: 4.7,
      reviewsCount: 95,
      priceLevel: '\$\$',
      photoUrl: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=600&q=80',
      lat: -23.548212,
      lng: -46.658392,
      tags: ['Croissants', 'Fermentação Natural', 'Brunch'],
      openingHours: '07:30 - 20:00',
    ),
    const Place(
      id: 'p4',
      name: 'Guarita Bar',
      category: 'Bar & Coquetelaria',
      address: 'Rua Simão Álvares, 952 - Pinheiros',
      neighborhood: 'Pinheiros',
      city: 'São Paulo',
      rating: 4.8,
      reviewsCount: 180,
      priceLevel: '\$\$\$',
      photoUrl: 'https://images.unsplash.com/photo-1514933651103-005eec06c04b?auto=format&fit=crop&w=600&q=80',
      lat: -23.560112,
      lng: -46.689431,
      tags: ['Drinques Autorais', 'Petiscos', 'Música'],
      openingHours: '18:00 - 01:00',
    ),
  ];

  static final List<Review> reviews = [
    Review(
      id: 'r1',
      placeId: 'p1',
      placeName: 'Mani',
      placeCategory: 'Restaurante Contemporâneo',
      placePhotoUrl: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=600&q=80',
      userId: 'user-1',
      userName: 'Camila Rossi',
      userHandle: '@camilagourmet',
      userAvatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=200&q=80',
      rating: 5.0,
      text: 'O menu degustação da chef Helena Rizzo é uma verdadeira obra de arte. O falso nhoque de mandioquinha com dashi de tucupi é inesquecível. Serviço impecável do início ao fim.',
      dishesOrdered: ['Falso Nhoque de Mandioquinha', 'Robalo no Vapor', 'Esfera de Jabuticaba'],
      favoriteDish: 'Falso Nhoque de Mandioquinha',
      companionTags: ['Jantar a dois', 'Ocasião Especial'],
      likesCount: 38,
      commentsCount: 6,
      hasLiked: true,
      createdAt: DateTime.now().subtract(const Duration(hours: 3)),
    ),
    Review(
      id: 'r2',
      placeId: 'p2',
      placeName: 'Coffee Lab',
      placeCategory: 'Cafeteria Especial',
      placePhotoUrl: 'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?auto=format&fit=crop&w=600&q=80',
      userId: 'user-me',
      userName: 'Pedro Otávio',
      userHandle: '@pedrootavio',
      userAvatarUrl: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=200&q=80',
      rating: 4.5,
      text: 'Ritual número 19 com café catuaí amarelo fermentado. As notas florais e de pêssego estavam muito nítidas. O bolo de brigadeiro com flor de sal completa a experiência.',
      dishesOrdered: ['Café Filtrado V60', 'Bolo de Brigadeiro', 'Pão de Queijo Canastra'],
      favoriteDish: 'Café Filtrado V60',
      companionTags: ['Sozinho', 'Foco / Leitura'],
      likesCount: 19,
      commentsCount: 2,
      hasLiked: false,
      createdAt: DateTime.now().subtract(const Duration(days: 1)),
    ),
  ];
}
